### ISSUE TITLE
Using unstable releases of mongoose

### ISSUE THREAD

**Issue by invernizzie** [iolo/mongoose-q#20]
In package.json, you specify the version range `^3.8.3` for mongoose. That includes 3.9.x, which is currently unstable (a big warning appears in terminal output when running anything using such a version). It should probably be `~3.8.3`, which will stay within 3.8.x.

If you agree, I'll gladly check that the warning indeed goas away, and issue a PR.

**Comment by iolo** [comment]
I totally agree with you. ;)
